### ISSUE TITLE
New maps needed

### ISSUE THREAD

**Issue by c-martinez** [NLeSC/nlesc-calendar#11]
@LourensVeen is working on that. Could you ping me (or send a PR) once they are done?

**Comment by LourensVeen** [comment]
Will do!

**Comment by LourensVeen** [comment]
Okay, I have some new map images, but it seems that the layout is dependent on them being a particular size in pixels. Is that something we want to have? Will it work on differently sized screens?

I can scale the new ones to be exactly as wide as the old ones if that's easiest, or pile on the pixels to make sure it never gets blocky...

**Comment by c-martinez** [comment]
I think the main use case will be to see this in a tablet hanging on the wall, so differently sized screens should hopefully not be too much of an issue.

I think making them as wide as the old ones might be indeed the easiest.

Thanks!

**Comment by LourensVeen** [comment]
I've pushed a  branch, `sp402-maps` with some new images of the same width as the old ones. It doesn't look right though, they're shifted a bit. Also, the image with both upstairs and downstairs doesn't seem to be used anywhere? I haven't replaced it yet, maybe it should just be deleted?

**Comment by c-martinez** [comment]
Fixed by #12
