### ISSUE TITLE
Run as a service on mac-mini

### ISSUE THREAD

**Issue by c-martinez** [NLeSC/nlesc-calendar#3]
How do we do that?

**Comment by nielsdrost** [comment]
http://stackoverflow.com/questions/23208708/how-to-start-python-file-as-a-service-in-osx-i-need-both-a-start-and-a-stop-scr#23217434

**Comment by nielsdrost** [comment]
It should run on port 80, and as the escience user, I think.

**Comment by c-martinez** [comment]
This may also work :-)

https://www.digitalocean.com/community/tutorials/how-to-set-up-django-with-postgres-nginx-and-gunicorn-on-centos-7#create-a-gunicorn-systemd-service-file

**Comment by c-martinez** [comment]
Running: 
```
/Users/escience/Downloads/nlesc-calendar/venv/bin/gunicorn --bind 0.0.0.0:80 server:app
```
(from workdir `/Users/escience/Downloads/nlesc-calendar/`) will make it start as a service. But I couldn't get it working straight away, so will have to give it another try later. Sorry!

**Comment by nielsdrost** [comment]
No need to be apologetic, It looks awesome :-)

For a more relaxing development experience you could rdesktop to the machine :-)

**Comment by c-martinez** [comment]
Done! -- calendar starts when user `escience` logs in.
